<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.3 (Python 3.13.4 on win32)" generated="2025-06-11T16:29:29.100889" rpa="false" schemaversion="5">
<suite id="s1" name="ExcelTutorial" source="C:\Users\dsara\PycharmProjects\PythonProject\DataDrivenTesting\ExcelTutorial.robot">
<kw name="Launch App" owner="DDTKeywords" type="SETUP">
<kw name="Open Browser" owner="SeleniumLibrary">
<msg time="2025-06-11T16:29:29.748776" level="INFO">Opening browser 'Firefox' to base url 'https://www.tutorialspoint.com/selenium/practice/selenium_automation_practice.php'.</msg>
<arg>${url}</arg>
<arg>${browser}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="PASS" start="2025-06-11T16:29:29.748336" elapsed="10.471675"/>
</kw>
<kw name="Maximize Browser Window" owner="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="PASS" start="2025-06-11T16:29:40.220513" elapsed="0.014651"/>
</kw>
<status status="PASS" start="2025-06-11T16:29:29.747276" elapsed="10.488104"/>
</kw>
<test id="s1-t1" name="Login with user ${username}" line="12">
<kw name="Invalid Login">
<msg time="2025-06-11T16:29:40.239773" level="FAIL">Variable '${email}' not found.</msg>
<arg>${email}</arg>
<arg>${mobile}</arg>
<arg>${dob}</arg>
<arg>${subject}</arg>
<arg>${address}</arg>
<arg>Default UserData</arg>
<status status="FAIL" start="2025-06-11T16:29:40.238160" elapsed="0.001740">Variable '${email}' not found.</status>
</kw>
<status status="FAIL" start="2025-06-11T16:29:40.236347" elapsed="0.004471">Variable '${email}' not found.</status>
</test>
<kw name="Close App" owner="DDTKeywords" type="TEARDOWN">
<kw name="Close Browser" owner="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<status status="PASS" start="2025-06-11T16:29:40.244985" elapsed="4.378933"/>
</kw>
<status status="PASS" start="2025-06-11T16:29:40.244641" elapsed="4.379502"/>
</kw>
<status status="FAIL" start="2025-06-11T16:29:29.106306" elapsed="15.517914"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="ExcelTutorial" id="s1" pass="0" fail="1" skip="0">ExcelTutorial</stat>
</suite>
</statistics>
<errors>
<msg time="2025-06-11T16:29:29.740642" level="ERROR">[ DataDriver ] Error in robot file:
  File "C:\Users\dsara\PycharmProjects\PythonProject\DataDrivenTesting\ExcelTutorial.robot", line 0</msg>
<msg time="2025-06-11T16:29:29.740993" level="ERROR">In source file:
  File "C:UsersdsaraPycharmProjectsPythonProjectTestDataDDTTutorial.xlsx", line 0</msg>
<msg time="2025-06-11T16:29:29.746062" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find C:\Users\dsara\PycharmProjects\PythonProject\DataDrivenTesting\UsersdsaraPycharmProjectsPythonProjectTestDataDDTTutorial.xlsx but file does not exist.</msg>
</errors>
</robot>
